// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBlNq-lk4AyNiJVbEWz-mdwmgwIBV1Qc',
    appId: '1:449134120819:web:3f3cb9dd39b870563f3f06',
    messagingSenderId: '449134120819',
    projectId: 'swallow-63849',
    authDomain: 'swallow-63849.firebaseapp.com',
    storageBucket: 'swallow-63849.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGVye4DdPtmJ1PzI6jBnxW-tRVbPxlJEc',
    appId: '1:449134120819:android:86a6efcc7784d7253f3f06',
    messagingSenderId: '449134120819',
    projectId: 'swallow-63849',
    storageBucket: 'swallow-63849.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCty9mz0K09sA4mr2s1GJE8RG7JnC7ok',
    appId: '1:449134120819:ios:b0549f050dd71b243f3f06',
    messagingSenderId: '449134120819',
    projectId: 'swallow-63849',
    storageBucket: 'swallow-63849.appspot.com',
    iosBundleId: 'com.example.swallow',
  );
}
